#!/usr/bin/env python
# encoding: utf-8

from pylab import *
import math
import numpy as np

g=9.8
s0m=4.1E-4
x=[]
y=[]
vx=[]
vy=[]
omega=0.
fx=[]
fy=[]
b2m=[]
v=[]
alpha=0.
dt=0.
i=1

def initialize(x,y,v,_alpha,vx,vy,_omega,_dt):
    global dt
    x.append(0)
    y.append(0)
    omega=2000*2*3.14159/60
    v.append(float(raw_input("initial velocity of the baseball -> ")))
    alpha=float(raw_input("initial angle of the baseball -> "))
    vx.append(v[0]*math.cos(math.radians(alpha)))
    vy.append(v[0]*math.sin(math.radians(alpha)))
    dt=float(2*vy[0]/g/100)
    print x,y,omega,v,alpha,vx,vy,dt

def calculate(b2m,fx,fy,vx,vy,x,y,i,v):
    while (y[i-1]>=0.): 
        b2m.append(0.0039+0.0058/(1+np.exp((v[i-1]-35)/5)))
        print b2m
        fx.append(b2m[i-1]*v[i-1]*vx[i-1])
        print fx
        fy.append(b2m[i-1]*v[i-1]*vy[i-1]-s0m*vx[i-1]*omega)
        vx.append(vx[i-1]-fx[i-1]*dt)
        vy.append(vy[i-1]-g*dt-fy[i-1]*dt)
        x.append(x[i-1]+vx[i-1]*dt)
        y.append(y[i-1]+vy[i-1]*dt)
        i=i+1
        v.append(vx[i-1]**2+vy[i-1]**2)
    return 0

initialize(x,y,v,alpha,vx,vy,omega,dt)
calculate(v,b2m,fx,fy,vx,vy,x,y,i)

plot(x,y,label='trejectory of batted ball')
legend(loc='upper center')
ylabel('vertical height y/m')
xlabel('herizonal distance x/m')


